version: "3"
services:
    alvara-backend:
        container_name: alvara-backend
        image: alvara-backend:latest
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - JAR_FILE=target/alvara-backend-1.0.jar
                - CONTEXT=alvara-backend
        ports:
            - 8090:8080
        restart: always
        env_file:
            - .env