version: "3"
services:
    alvara-backend:
        container_name: alvara-backend
        image: alvara-backend:latest
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - JAR_FILE=target/alvara-backend-1.0.jar
                - CONTEXT=alvara-backend
        ports:
            - 8090:8080
        restart: always
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://cloudtecnologia.dynns.com:5432/alvara-hml
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: 895674
            SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
            SPRING_HIBERNATE_FORMAT-SQL: "true"
            SPRING_HIBERNATE_SHOW-SQL: "false"
            SPRING_HIBERNATE_DDL-AUTO: update