spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  info:
    app:
      version: ${SPRING_APPLICATION_VERSION}
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
    properties:
      hibernate:
        format_sql: ${SPRING_HIBERNATE_FORMAT_SQL}
        show_sql: ${SPRING_HIBERNATE_SHOW_SQL}
    hibernate:
      ddl-auto: ${SPRING_HIBERNATE_DDL_AUTO}
  security:
    enabled: ${SPRING_SECURITY_ENABLED}

security:
  oauth2:
    client:
      scope: password
  jwt:
    signing-key: ${SECURITY_JWT_KEY}
    expiration_token_minutes: ${SECURITY_JWT_EXPIRATION}
    client_id: ${SECURITY_JWT_CLIENT_ID}
    client_secret: ${SECURITY_JWT_CLIENT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

scrape_configs:
  - job_name: 'spring-boot-app'
    static_configs:
      - targets: ['localhost:8080']

logging:
  file:
    name: ./logs/log-file.log
  level:
    root: ${LOGGING_FILE_LEVEL_ROOT}
# trace -  detalhado (Consome muito recurso)
# debug - informações de depuração
# warn - Avisos de advertencia (Memoria topando etc)


springdoc:
  override-with-generic-response: false