spring:
  profiles:
    active: local
  application:
    name: Sistema de Alvarás WEB
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  security:
    enabled: ${spring.profiles.active != 'test'}
security:
  oauth2:
    client:
      scope: password
  jwt:
    signing-key: cm9uYWxkaW5obw==
    expiration_token_minutes: 30
    client_id: my-angular-app
    client_secret: '@321'