spring:
  profiles:
    active: production
  application:
    name: Sistema de Alvarás WEB
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  info:
    app:
      version: 2024.08.10