spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5431/
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ??
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    hibernate:
      ddl-auto: update