spring:
  datasource:
    url: jdbc:postgresql://cloudtecnologia.dynns.com:5432/alvara-hml
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 895674
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    hibernate:
      ddl-auto: update
  security:
    enabled: true
security:
  oauth2:
    client:
      scope: password
  jwt:
    signing-key: cm9uYWxkaW5obw==
    expiration_token_minutes: 30
    client_id: my-angular-app
    client_secret: '@321'